/** Exercise the public UI without a runtime host or project writes. */
import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser = await chromium.launch({headless:true});
const page = await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{if(!localStorage.getItem('biobuzz-twin'))localStorage.setItem('biobuzz-twin',JSON.stringify({runtimeEnabled:false,settingsAutoLoad:false,pip:false,stadium:false,opponents:false}));});
await page.goto('http://localhost:5173/?ci=1');
await page.waitForFunction(()=>!!window.__twin, {timeout:30000});
await page.screenshot({path:'/tmp/biobuzz-new-practice.png'});
console.log('Practice workspace loaded.');
await page.getByRole('button',{name:'Start timed match',exact:true}).click();
await page.waitForFunction(()=>/^(AUTO|TRANSITION|TELEOP|ENDGAME)/.test(document.querySelector('.match-clock')?.textContent??''));
const time=await page.locator('.match-clock').innerText();
await page.waitForFunction(t=>document.querySelector('.match-clock')?.textContent!==t,time);
await page.getByRole('button',{name:'Stop match',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('.match-clock')?.textContent.includes('MATCH STOPPED'));
assert.equal(await page.locator('.shot-at-glance').isVisible(),true);
assert.match(await page.locator('.shot-at-glance').innerText(),/Required:.*RPM/);
await page.locator('#workspace-header').getByRole('button',{name:'About',exact:true}).click();
await page.getByRole('dialog',{name:'About Camels Hump Coders'}).waitFor();
assert.equal(await page.getByRole('heading',{name:'Camels Hump Coders #36682',exact:true}).isVisible(),true);
await page.getByRole('dialog',{name:'About Camels Hump Coders'}).getByRole('button',{name:'Close',exact:true}).click();

assert.equal(errors.length,0, errors.join('\n'));
await page.getByRole('button',{name:'All settings',exact:true}).click();
await page.getByRole('searchbox',{name:'Search all settings'}).fill('Hood angle');
await page.getByRole('spinbutton',{name:'Hood angle (°)',exact:true}).fill('60');
await page.getByRole('spinbutton',{name:'Hood angle (°)',exact:true}).press('Tab');
await page.waitForFunction(()=>window.__twin.state.robot.launcher.elevationDeg===60);
await page.getByRole('button',{name:'↶ Undo edit',exact:true}).click();
await page.waitForFunction(()=>window.__twin.state.robot.launcher.elevationDeg===55);
await page.getByRole('button',{name:'↷ Redo',exact:true}).click();
await page.waitForFunction(()=>window.__twin.state.robot.launcher.elevationDeg===60);
await page.getByRole('button',{name:'Pin Hood angle (°)',exact:true}).click();
await page.getByRole('button',{name:'Practice',exact:true}).click();
assert.equal(await page.locator('.pinned-settings').getByRole('spinbutton',{name:'Hood angle (°)'}).count(),1);
await page.locator('.pinned-settings').getByRole('spinbutton').focus();
await page.keyboard.press('Tab');
assert.notEqual(await page.evaluate(()=>document.activeElement.tagName),'BODY');
await page.getByRole('button',{name:'Try a sample setup',exact:true}).click();
await page.getByRole('button',{name:'Aim at target · R',exact:true}).click();
await page.getByRole('button',{name:'Shoot · Space',exact:true}).click();
await page.waitForFunction(()=>window.__twin.stats().shotsFired>0);
await page.reload();
await page.waitForFunction(()=>!!window.__twin);
await page.getByRole('button',{name:'Restore my setup',exact:true}).click();
await page.waitForFunction(()=>window.__twin.state.robot.launcher.elevationDeg===60);
await page.getByRole('button',{name:'Tune',exact:true}).click();
await page.getByRole('button',{name:'Calibration',exact:true}).click();
await page.getByRole('button',{name:'2. Measure',exact:true}).click();
await page.getByRole('spinbutton',{name:'Impact height (in)',exact:true}).fill('62');
await page.getByRole('spinbutton',{name:'Impact height (in)',exact:true}).press('Tab');
await page.getByRole('button',{name:'Add shot',exact:true}).click();
await page.waitForFunction(()=>window.__twin.state.calibration.shots.length===1);
await page.getByRole('button',{name:'3. Review & apply',exact:true}).click();
await page.getByRole('button',{name:'Apply to twin',exact:true}).waitFor();
// Restore the empty state to check that it never claims a fit has been applied.
page.once('dialog',d=>d.accept());
await page.locator('details[data-title="Shooter calibration"]').getByRole('button',{name:'Clear',exact:true}).click();
await page.getByRole('button',{name:'Add measurements to fit',exact:true}).waitFor();
await page.screenshot({path:'/tmp/biobuzz-new-calibration.png'});
await page.getByRole('button',{name:'Replay',exact:true}).click();
await page.locator('#replay-dock').getByRole('button',{name:'⏮ 1 s',exact:true}).click();
await page.waitForFunction(()=>window.__twin.recorder.cursor!==undefined);
await page.locator('#view').focus(); await page.keyboard.press('w');
assert.equal(await page.evaluate(()=>window.__twin.recorder.cursor!==undefined),true);
await page.locator('#control-dock').getByRole('button',{name:'Return to live',exact:true}).click();
await page.waitForFunction(()=>window.__twin.recorder.cursor===undefined);
await page.getByRole('button',{name:'Run TeamCode',exact:true}).click();
await page.screenshot({path:'/tmp/biobuzz-new-runtime.png'});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'/tmp/biobuzz-new-mobile.png'});
await page.getByRole('button',{name:'Hide sidebar',exact:true}).click();
await page.waitForFunction(()=>window.__twinRenderCount>0);
await page.screenshot({path:'/tmp/biobuzz-new-mobile-field.png'});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
assert.equal(errors.length,0,errors.join('\n'));
console.log('UX smoke passed: settings, undo/redo, pins, keyboard, sample, shooting, calibration, replay, mobile.');
await browser.close();
